### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by nmatison** [nmatison/Jetsy#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Adequate and appropriate seeds
- [x] Smooth, bug-free navigation

**Comment by ryan-mapa** [comment]
Some action items:
- [x] style errors
- [x] consider changing the modal messages "Register to continue" to "Register" depending on how you reach the modal.
- [x] add a space on left side of input fields
- [x] consider changing input type for email field to type='email'
- [x] did you decide to sign in with username over email?

NIce work so far! Lookin good!

**Comment by nmatison** [comment]
I think I got it all, and yes, I want to go with the username for the login.

**Comment by ryan-mapa** [comment]
Just a couple things:
- Form inputs are a little wider than buttons. Should align exactly.
- Center errors

**Comment by nmatison** [comment]
Okay, I did both, but fyi Etsy's error's are not centered on their modal. Either way works for me though
